<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AttemptReview\**" />
    <Compile Remove="LoginAPI\**" />
    <EmbeddedResource Remove="AttemptReview\**" />
    <EmbeddedResource Remove="LoginAPI\**" />
    <None Remove="AttemptReview\**" />
    <None Remove="LoginAPI\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="AttemptReview\AttemptReview.csproj" />
    <ProjectReference Include="LoginAPI\LoginAPI.csproj" />
  </ItemGroup>

</Project>
